<?php // generated by https://www.devsense.com/

/**
 * Gets line from file pointer and parse for CSV fields
 * Similar to fgets() except that fgetcsv() parses the line it reads for fields in CSV format and returns an array containing the fields read.
 *
 * @param resource $stream A valid file pointer to a file successfully opened by fopen(), popen(), or fsockopen().
 * @param int|null $length Must be greater than the longest line (in characters) to be found in the CSV file (allowing for trailing line-end characters). Otherwise the line is split in chunks of `length` characters, unless the split would occur inside an enclosure. Omitting this parameter (or setting it to 0, or `null` in PHP 8.0.0 or later) the maximum line length is not limited, which is slightly slower.
 * @param string $separator The `separator` parameter sets the field separator. It must be a single byte character.
 * @param string $enclosure The `enclosure` parameter sets the field enclosure character. It must be a single byte character.
 * @param string $escape The `escape` parameter sets the escape character. It must be a single byte character or the empty string. The empty string (`""`) disables the proprietary escape mechanism. Note : Usually an `enclosure` character is escaped inside a field by doubling it; however, the `escape` character can be used as an alternative. So for the default parameter values `""` and `\"` have the same meaning. Other than allowing to escape the `enclosure` character the `escape` character has no special meaning; it isn't even meant to escape itself. Warning As of PHP 8.4.0, depending on the default value of `escape` is deprecated. It needs to be provided explicitly either positionally or by the use of named arguments .
 * @return array|bool Returns an indexed array containing the fields read on success, or `false` on failure.
 */
function fgetcsv($stream, int $length = null, string $separator = ";", string $enclosure = "\"", string $escape = "\\"): object {
	// function body is hidden
	return new stdClass(); // Ensure a return value
}